### ISSUE TITLE
zone_ids off for Chelsea + Westborough

### ISSUE THREAD

**Issue by stevenpandrews** [mbta/gtfs-documentation#22]
It looks like the `zone_id` the `stop.txt` file for Chelsea (CR-zone-4, should be CR-zone-1A) and Westborough (CR-zone-8, should be CR-zone-7) are incorrect. 

gtfs_file: https://cdn.mbtace.com/archive/20190718.zip
Chelsea: https://www.mbta.com/stops/place-ER-0046
Westborough: https://www.mbta.com/stops/place-WML-0340

**Comment by paulswartz** [comment]
Thanks for noting this! We'll work on fixing the GTFS.

**Comment by paulswartz** [comment]
This has been fixed in the latest GTFS. Thanks for letting us know!
